# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake

on:
  workflow_dispatch:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

# When pushing new commits, cancel any running builds on that branch
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: contains(toJson(github.event.commits), '[ci skip]') == false
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-2019, macos-12]

    steps:
    - name: Linux Build
      if: runner.os == 'Linux'
      run: |
		 docker build -t STR_X .
		 docker run -it -v $(pwd):/src STR_X

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: seanmiddleditch/gha-setup-ninja@master
    - run: cmake -Bbuild -GNinja -DPRODUCTION_BUILD=1 -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

    - name: Build
      run: cmake --build build --config Release

    - name: Validate Unix
      if: runner.os != 'Windows'
      run: ./validate.sh
    - name: Validate Windows
      if: runner.os == 'Windows'
      run: bash validate.sh
