name: Deploy

on:
  workflow_run:
    workflows: ["Cmake"]
    types: [completed]
    branches: ["master"]
  workflow_dispatch:

env:
  PROJECT: STR-X
  ARTIFACTS_PATH: build/STR-X_artefacts/Release/

jobs:
  build_and_deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && ${{ 
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          include:
            - name: Linux
              os: ubuntu-20.04
            - name: macOS
              os: macos-12
            - name: Windows
              os: windows-2019

    steps:

    - name: Install Linux Deps
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install libasound2-dev libx11-dev \
          libxcomposite-dev libxcursor-dev libxext-dev libxinerama-dev \
          libxrandr-dev libxrender-dev libfreetype6-dev libglu1-mesa-dev \
          libjack-jackd2-dev ninja-build

    - name: Windows Install Ninja
      if: runner.os == 'Windows'
      run: |
        choco install ninja

    - name: MacOS Install Tools
      if: runner.os == 'macOS'
      run: |
        brew install ninja packages

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Checkout build scripts
      uses: actions/checkout@v3
      with:
        repository: ArborealAudio/scripts
        ref: deploy
        path: scripts
        token: ${{ secrets.WORKFLOW_PAT }}

    - name: Get SDKs
      uses: actions/checkout@v3
      with:
        repository: ArborealAudio/vst2_sdk
        path: vst2_sdk
        token: ${{ secrets.WORKFLOW_PAT }}

    - name: Import App Certs (MacOS)
      uses: apple-actions/import-codesign-certs@v2
      if: runner.os == 'macOS'
      with:
        keychain-password: ${{ secrets.DEV_ID_APP_PASSWORD }}
        p12-file-base64: ${{ secrets.DEV_ID_APP_CERT }}
        p12-password: ${{ secrets.DEV_ID_APP_PASSWORD }}

    - name: Import Installer Certs (MacOS)
      uses: apple-actions/import-codesign-certs@v2
      if: runner.os == 'macOS'
      with:
        keychain-password: ${{ secrets.DEV_ID_APP_PASSWORD }}
        p12-file-base64: ${{ secrets.DEV_ID_INSTALLER_CERT }}
        p12-password: ${{ secrets.DEV_ID_INSTALLER_PASSWORD }}
        create-keychain: 'false'

    - name: Build (MacOS)
      if: runner.os == 'macOS'
      env:
        APP_CERT: ${{ secrets.DEVELOPER_ID_APPLICATION }}
        INSTALL_CERT: ${{ secrets.DEVELOPER_ID_INSTALLER }}
        APPLE_USER: ${{ secrets.NOTARY_USER }}
        NOTARY_PW: ${{ secrets.NOTARY_PASSWORD }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
        VERSION: "1.2.1"
      run: |
        ./scripts/mac-build.sh -n STR-X -v $VERSION --clap --vst2
        echo "VERSION=$VERSION" >> "$GITHUB_ENV"
        echo "INSTALLER_PATH=installer/build/${{ env.PROJECT }}-mac.dmg" >> "$GITHUB_ENV"

    - name: Build (Linux)
      if: runner.os == 'Linux'
      env:
        VERSION: "1.2.1"
      run: |
        cmake -Bbuild -GNinja -DPRODUCTION_BUILD=1 -DBUILD_VST2=1
        cmake --build build --config Release
        ./scripts/linux-installer.sh -n STR-X -v $VERSION --clap --vst2
        echo "VERSION=$VERSION" >> "$GITHUB_ENV"
        echo "INSTALLER_PATH=${{ env.PROJECT }}-linux-v${{ env.VERSION }}.tar.xz" >> "$GITHUB_ENV"
      
    - name: Build (Windows)
      if: runner.os == 'Windows'
      env:
        VERSION: "1.2.1"
      shell: bash
      run: |
        scripts/win-build.sh -n STR-X -v $VERSION --clap --vst2 --ninja
        echo "INSTALLER_PATH=products/Output/${{ env.PROJECT }}-windows.exe" >> "$GITHUB_ENV"

    - name: Sign Windows Installer
      if: runner.os == 'Windows'
      uses: GabrielAcostaEngler/signtool-code-sign@main
      with:
        certificate: ${{ secrets.WIN_INSTALL_CERT }}
        cert-password: ${{ secrets.WIN_INSTALL_CERT_PW }}
        cert-sha1: ${{ secrets.WIN_INSTALL_CERT_HASH }}
        folder: products/Output
        timestamp-server: 'http://timestamp.digicert.com'

    - name: Upload to S3
      uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_bucket: arborealaudioinstallers
        source_dir: ${{ env.INSTALLER_PATH }}
        destination_dir: str-x
