name: Deploy

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          include:
            - os: ubuntu-20.04
              cc: clang-12
              c++: clang++-12
              formats: [VST3, CLAP, LV2]

    steps:

    - name: Install Linux Deps
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install libasound2-dev libx11-dev \
          libxcomposite-dev libxcursor-dev libxext-dev libxinerama-dev \
          libxrandr-dev libxrender-dev libfreetype6-dev libglu1-mesa-dev \
          libjack-jackd2-dev ninja-build

    # TODO: Install Ninja on MacOS/Windows

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure
      env:
        CMAKE_C_COMPILER=${{ matrix.cc }}
        CMAKE_CXX_COMPILER=${{ matrix.c++ }}
      run: |
        cmake -Bbuild -GNinja -DPRODUCTION_BUILD=1

    - name: Build
      run: |
        cmake --build build --config Release --parallel 4

    - name: Get artifacts
      run: |
        echo >> "ARTIFACTS_PATH=build/${{ env.PRODUCT_NAME }}_artefacts/Release/" >> $GITHUB_ENV

    - name: Compress
      working-directory: ${{ env.ARTIFACTS_PATH }}
      run: |
        tar cfJ "${{ env.PRODUCT_NAME }}-linux.tar.xz ${{ env.ARTIFACTS_PATH }}/${{ matrix.formats }}

    - name: Upload Linux
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.PRODUCT_NAME }}-linux.tar.xz
        path: ${{ env.ARTIFACTS_PATH }}/${{ env.PRODUCT_NAME}}-linux.tar.xz
