name: Deploy

on:
  workflow_dispatch:

# concurrency:
	# group: ${{ github.ref }}
	# cancel-in-progress: true

jobs:
  build_and_deploy:
	runs-on: ubuntu-20.04
	strategy:
	  fail-fast: false

	steps:

    - name: Test
      run: |
        echo "I am running"
