name: Deploy

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    strategy:
        fail-fast: false

    steps:

    - name: Test
      run: |
        echo "I am running"
