name: Deploy

on:
  workflow_dispatch:

env:
  PROJECT: STR-X
  ARTIFACTS_PATH: build/STR-X_artefacts/Release/

jobs:
  build_and_deploy:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          include:
            - os: ubuntu-20.04
              cmake_args: "-DCMAKE_C_COMPILER=cc -DCMAKE_CXX_COMPILER=c++"
              clang_version: 12
            - os: macos-12
            - os: windows-2019
              cmake_args: "-DCMAKE_C_COMPILER=cc -DCMAKE_CXX_COMPILER=c++"
              clang_version: latest

    steps:

    - name: Setup Clang
      if: runner.os != 'macOS'
      uses: egor-tensin/setup-clang@v1
      with:
        version: ${{ matrix.clang_version }}

    - name: Install Linux Deps
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install libasound2-dev libx11-dev \
          libxcomposite-dev libxcursor-dev libxext-dev libxinerama-dev \
          libxrandr-dev libxrender-dev libfreetype6-dev libglu1-mesa-dev \
          libjack-jackd2-dev ninja-build

    - name: Windows Install Ninja
      if: runner.os == 'Windows'
      run: |
        choco install ninja

    - name: MacOS Install Ninja
      if: runner.os == 'macOS'
      run: |
        brew install ninja

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure
      run: |
        cmake -Bbuild -GNinja -DPRODUCTION_BUILD=1 ${{ matrix.cmake_args }}

    - name: Build
      run: |
        cmake --build build --config Release --parallel 4

    - name: Compress Linux
      working-directory: ${{ env.ARTIFACTS_PATH }}
      run: |
        tar cfJ "${{ env.PROJECT }}-linux.tar.xz" ./VST3/${{ env.PROJECT}}.vst3 ./LV2/${{ env.PROJECT}}.lv2 ./CLAP/${{ env.PROJECT }}.clap

    - name: Compress MacOS
      working-directory: ${{ env.ARTIFACTS_PATH }}
      run: |
        tar cfJ "${{ env.PROJECT }}-macos.tar.xz" ./VST3/${{ env.PROJECT}}.vst3 ./AU/${{ env.PROJECT}}.component ./CLAP/${{ env.PROJECT }}.clap

    - name: Compress Windows
      working-directory: ${{ env.ARTIFACTS_PATH }}
      run: |
        7z a -tzip "${{ env.PROJECT }}-windows.zip" ./VST3/${{ env.PROJECT}}.vst3 ./CLAP/${{ env.PROJECT }}.clap

    - name: Upload Linux
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.PROJECT }}-linux.tar.xz
        path: ${{ env.ARTIFACTS_PATH }}/${{ env.PROJECT}}-linux.tar.xz

    - name: Upload MacOS
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.PROJECT }}-macos.tar.xz
        path: ${{ env.ARTIFACTS_PATH }}/${{ env.PROJECT}}-macos.tar.xz

    - name: Upload Windows
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.PROJECT }}-windows.zip
        path: ${{ env.ARTIFACTS_PATH }}/${{ env.PROJECT}}-windows.zip
